// <auto-generated />
using System;
using CouponCode.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CouponCode.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240517111743_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CouponCode.model.coupenDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("coupenCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("coupen", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
